export type GearItem = {
  id: number;
  name: string;
  description: string;
  quantity: string;
  category: string;
  icon: string; // lucide icon name
};

export const gearCategories = [
  { id: "all", label: "All" },
  { id: "head", label: "Head" },
  { id: "clothing", label: "Clothing" },
  { id: "footwear", label: "Footwear" },
  { id: "camp", label: "Camp" },
  { id: "accessories", label: "Accessories" },
  { id: "safety", label: "Safety" },
];

export const gearItems: GearItem[] = [
  {
    id: 1,
    icon: "Glasses",
    name: "Sunglasses",
    description: "UV protected.",
    quantity: "1–2 pairs",
    category: "head",
  },
  {
    id: 2,
    icon: "Waves",
    name: "Warm beanie",
    description: "Thick enough to keep warm in 4–7°C.",
    quantity: "1",
    category: "head",
  },
  {
    id: 3,
    icon: "Sun",
    name: "Hat or cap",
    description: "To protect from sunlight.",
    quantity: "1",
    category: "head",
  },
  {
    id: 4,
    icon: "Wind",
    name: "Buff",
    description:
      "Light and soft to cover your face while cleaning boulders and protect from cold winds.",
    quantity: "2 pairs",
    category: "head",
  },
  {
    id: 5,
    icon: "Layers",
    name: "Thermals (upper and lower)",
    description: "Warm, soft, flexible, and quick-dry.",
    quantity: "2 pairs",
    category: "clothing",
  },
  {
    id: 6,
    icon: "Shirt",
    name: "Under garment",
    description: "—",
    quantity: "—",
    category: "clothing",
  },
  {
    id: 7,
    icon: "Minus",
    name: "Socks",
    description: "Warm and thick as well as thin ones.",
    quantity: "6 pairs",
    category: "clothing",
  },
  {
    id: 8,
    icon: "Footprints",
    name: "Slippers",
    description: "Comfortable enough for mornings, evenings, and camping.",
    quantity: "1 pair",
    category: "footwear",
  },
  {
    id: 9,
    icon: "Footprints",
    name: "Trekking shoes",
    description: "Proper trekking shoes with Vibram sole.",
    quantity: "1 pair",
    category: "footwear",
  },
  {
    id: 10,
    icon: "Mountain",
    name: "Climbing shoes",
    description: "Dedicated shoes for mountain climbing up to 6000m.",
    quantity: "1 pair",
    category: "footwear",
  },
  {
    id: 11,
    icon: "Tent",
    name: "Sleeping bag",
    description: "Down filled, graded comfort at −10 to −20°C.",
    quantity: "1",
    category: "camp",
  },
  {
    id: 12,
    icon: "Layers",
    name: "Mid-layer",
    description: "Good enough to allow movement — jacket or jumper.",
    quantity: "2 pairs",
    category: "clothing",
  },
  {
    id: 13,
    icon: "Shirt",
    name: "T-shirt",
    description: "Quick-dry and light.",
    quantity: "3–4 pairs",
    category: "clothing",
  },
  {
    id: 14,
    icon: "CloudSnow",
    name: "Down jacket",
    description: "For ~5°C, mostly during evening and night.",
    quantity: "2 pairs",
    category: "clothing",
  },
  {
    id: 15,
    icon: "Columns2",
    name: "Pants",
    description: "Flexible and warm.",
    quantity: "2–3 pairs",
    category: "clothing",
  },
  {
    id: 16,
    icon: "Columns2",
    name: "Shorts",
    description: "Quick-dry.",
    quantity: "1–2 pairs",
    category: "clothing",
  },
  {
    id: 17,
    icon: "Wind",
    name: "Soft shell pant and jacket",
    description: "Keeps warm from cold winds during hiking or climbing.",
    quantity: "1 pair each",
    category: "clothing",
  },
  {
    id: 18,
    icon: "Hand",
    name: "Gloves",
    description: "One thin fleece glove and one thick mountaineering glove.",
    quantity: "1 pair each",
    category: "clothing",
  },
  {
    id: 19,
    icon: "PersonStanding",
    name: "Hiking poles",
    description: "Rigid and mountaineering graded.",
    quantity: "1 pair",
    category: "accessories",
  },
  {
    id: 20,
    icon: "Flashlight",
    name: "Headlamp",
    description: "Small and practical, any type.",
    quantity: "1",
    category: "accessories",
  },
  {
    id: 21,
    icon: "Droplets",
    name: "Water bottle",
    description: "Nalgene is recommended.",
    quantity: "1",
    category: "accessories",
  },
  {
    id: 22,
    icon: "Shield",
    name: "Hard shell pants and jacket",
    description: "Dedicated hardshell: flexible, waterproof, breathable.",
    quantity: "1",
    category: "clothing",
  },
  {
    id: 23,
    icon: "HardHat",
    name: "Mountaineering helmet",
    description: "UIAA certified, any brand.",
    quantity: "1",
    category: "safety",
  },
  {
    id: 24,
    icon: "Link",
    name: "Alpine harness",
    description: "UIAA certified, dedicated to mountaineering.",
    quantity: "1",
    category: "safety",
  },
];
